version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4.1 # define version of docker image to use when it build project.
    steps: # define all step when circleCI along running.
      - checkout
      - run:
        name: Run firts time to build
        command: echo "Hello world"
      - run:
        name: Run last time to build
        command: echo "hello world step 2"

