version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4.1 # define version of docker image to use when it build project.
    steps: # define all step when circleCI along running.
      - checkout
      - run:
        name: First init
        command: echo "hello"